typography_spectrum: 0.019162912154570222
color:
  brandStrength: 0.29133934690617025
  lightness: 0.7944190071430057
  saturation: 0.4427289506420493
  rhythmicContrast: 0.43322217278182507
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
layout_spectrum: 0.07559985294938087
name: Rush Hour Traffic Jam
navigation:
  - name: Visualized Design
    url: 'https://goo.gl/images/SCyzOt'
    type: external
title: Route Junction
description: Slow down or point to bypass
